import { NextResponse } from 'next/server';
import dbConnect from '../../../../../lib/dbConnect';
import Project, { normalizeProject } from '../../../../../models/Project';

export async function GET(req: Request, { params }: { params: Promise<{ id: string }> }) {
  await dbConnect();
  try {
    const { id } = await params;
    const rawProject = await Project.findById(id).lean();
    if (!rawProject) return NextResponse.json({ error: 'Not found' }, { status: 404 });

    const p = normalizeProject(rawProject);

    const filename = `${(p.basicInfo?.name || 'project').toLowerCase().replace(/[^a-z0-9]+/g, '-')}-spec.md`;

    // Format markdown spec
    const markdown = `# ${p.basicInfo?.name || 'Project'} — Production Specification
> Generated by Forge Agency Operating System on ${new Date().toISOString().split('T')[0]}
> **Client:** ${p.basicInfo?.clientName || 'N/A'} | **Status:** ${p.status} | **Readiness Score:** ${p.readinessScore}%

---

## 1. Executive Summary & Overview
${p.basicInfo?.description || 'No description provided.'}

- **Website:** ${p.basicInfo?.website || 'Not specified'}
- **Target Platforms:** ${p.basicInfo?.targetPlatforms?.join(', ') || 'Web'}
- **Readiness Score:** ${p.readinessScore}%
${p.deliveryEstimate ? `- **Delivery Estimation:** ${p.deliveryEstimate.estimatedWeeks} weeks (${p.deliveryEstimate.totalDays} dev-days across ${p.deliveryEstimate.allocatedTeamSize} team members)` : ''}

---

## 2. Product DNA & Competitor Benchmarks
${p.dna?.persistentInstructions ? `### Persistent Directives\n${p.dna.persistentInstructions}\n` : ''}

### Competitors
${p.dna?.competitors?.length ? p.dna.competitors.map((c: string) => `- ${c}`).join('\n') : '*No competitors recorded.*'}

### Reference Benchmarks
${p.dna?.references?.length ? p.dna.references.map((r: any) => `- **[${r.name}](${r.url})**: ${r.notes || 'Reference benchmark'}`).join('\n') : '*No references recorded.*'}

---

## 3. Brand Identity & Guardrails
### Personality & Tone
- **Personality:** ${p.brand?.personality?.join(', ') || 'Not specified'}
- **Visual Style:** ${p.brand?.visualStyle || 'Modern minimal'}
- **Voice & Tone:** ${p.brand?.tone || 'Professional'}

### Palette Tokens
${p.brand?.colors?.length ? p.brand.colors.map((c: any) => `- \`${c.hex}\` — **${c.role}** *(Source: ${c.source})*`).join('\n') : '*No color palette defined.*'}

### Operational Guardrails
#### ALWAYS Enforce
${p.guardrails?.always?.length ? p.guardrails.always.map((g: any) => `- [x] ${g.text} *(Source: ${g.source})*`).join('\n') : '*No always guardrails.*'}

#### NEVER Allow
${p.guardrails?.never?.length ? p.guardrails.never.map((g: any) => `- [ ] ⛔ ${g.text} *(Source: ${g.source})*`).join('\n') : '*No never guardrails.*'}

---

## 4. Grounded Technical Architecture
${p.technicalPlan ? `
### Frontend Layer
- **Recommendation:** ${p.technicalPlan.frontend?.recommendation || 'Next.js 15'}
- **Rationale:** ${p.technicalPlan.frontend?.rationale || 'Server-side rendering and edge routing.'}
- **Capability Match:** ${p.technicalPlan.frontend?.capabilityMatch || 'Aligned with agency stack'}
- **Approval:** ${p.technicalPlan.frontend?.isApproved ? '✅ Approved for Production' : '⏳ In Review'}

### Backend Layer
- **Recommendation:** ${p.technicalPlan.backend?.recommendation || 'Next.js API & Route Handlers'}
- **Rationale:** ${p.technicalPlan.backend?.rationale || 'Colocated serverless logic.'}
- **Capability Match:** ${p.technicalPlan.backend?.capabilityMatch || 'Aligned with agency stack'}
- **Approval:** ${p.technicalPlan.backend?.isApproved ? '✅ Approved for Production' : '⏳ In Review'}

### Database Layer
- **Recommendation:** ${p.technicalPlan.database?.recommendation || 'MongoDB Atlas'}
- **Rationale:** ${p.technicalPlan.database?.rationale || 'Flexible dynamic document schema.'}
- **Capability Match:** ${p.technicalPlan.database?.capabilityMatch || 'Aligned with agency stack'}
- **Approval:** ${p.technicalPlan.database?.isApproved ? '✅ Approved for Production' : '⏳ In Review'}

### Authentication & Infrastructure
- **Auth:** ${p.technicalPlan.auth?.recommendation || 'Auth.js'} (${p.technicalPlan.auth?.isApproved ? 'Approved' : 'Pending'})
- **Infrastructure:** ${p.technicalPlan.infrastructure?.recommendation || 'Vercel'} (${p.technicalPlan.infrastructure?.isApproved ? 'Approved' : 'Pending'})

### Third-Party Integrations
${p.technicalPlan.integrations?.length ? p.technicalPlan.integrations.map((i: any) => `- **${i.name}**: ${i.rationale} (${i.isApproved ? 'Approved' : 'Pending'})`).join('\n') : '*No integrations specified.*'}
` : '*Technical plan pending generation.*'}

---

## 5. Feature Breakdown & Layered Engineering Tasks
${p.features?.length ? p.features.map((f: any) => `
### Feature: ${f.name} [Status: ${f.status}]
${f.description ? `> ${f.description}\n` : ''}
| Task ID | Layer | Title | Role | Est. Days | Priority | Status |
|---|---|---|---|---|---|---|
${f.tasks?.map((t: any) => `| \`${t.id}\` | **${t.layer}** | ${t.title} | ${t.assignedRole} | ${t.estimateDays}d | ${t.priority} | ${t.status === 'Done' ? '✅ Done' : t.status === 'In Progress' ? '⏳ In Progress' : '⚪ Todo'} |`).join('\n')}
`).join('\n') : '*No feature backlog generated.*'}

---

## 6. Git Health & Velocity Monitor
- **Repository URL:** ${p.gitIntegration?.repoUrl || 'Not connected'}
- **Active Branch:** \`${p.gitIntegration?.branch || 'main'}\`
- **Total Ingested Commits:** ${p.gitIntegration?.commits?.length || 0}
${p.gitIntegration?.aiHealthAnalysis ? `
### AI Drift Telemetry
- **Drift Score:** **${p.gitIntegration.aiHealthAnalysis.driftScore}% Alignment**
- **Last Evaluated:** ${new Date(p.gitIntegration.aiHealthAnalysis.lastAnalyzedAt).toLocaleString()}
- **Actionable Insights:**
${p.gitIntegration.aiHealthAnalysis.insights.map((ins: string) => `  - 💡 ${ins}`).join('\n')}
- **Dormant Features:** ${p.gitIntegration.aiHealthAnalysis.dormantFeatures.length ? p.gitIntegration.aiHealthAnalysis.dormantFeatures.join(', ') : 'None (all features active)'}
` : ''}

---
*Generated by Forge Agency Operating System. Grounded in Parker Studio Organization Intelligence.*
`;

    return new NextResponse(markdown, {
      status: 200,
      headers: {
        'Content-Type': 'text/markdown; charset=utf-8',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    });
  } catch (error: any) {
    console.error('GET /api/projects/[id]/export error:', error);
    return NextResponse.json({ error: 'Failed to export specification' }, { status: 500 });
  }
}
